name: Deploy

on:
  push:
    branches:
      - main
  # enables manual deploy
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build the site
        run: rake

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages
          folder: _site
